### ISSUE TITLE
Restore Favorites Button

### ISSUE THREAD

**Issue by joshuacant** [elfbutt/koreader-coverbrowserclean#20]
And make the USB toggle trigger on a long-press

**Comment by elfbutt** [comment]
https://github.com/elfbutt/koreader-coverbrowserclean/commit/19ee2ccbad82fef193e982537bbfbf9637670377

I brought back the fav icon, but instead of setting hold on that to usb prompt, I made it open the folder shortcuts screen. It's like favorites for folders!

I set the plus menu's hold to open the usb prompt.
